version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 9002:5432

    environment:
      - POSTGRES_DB=ivity
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 9003:8080

volumes:
  pgdata:
    external: true